/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Platform = IDL.Variant({
  'soundcloud' : IDL.Null,
  'other' : IDL.Text,
  'spotify' : IDL.Null,
  'youtube' : IDL.Null,
  'appleMusic' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageUpdate = IDL.Record({
  'id' : IDL.Text,
  'updatedContent' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const BeatStyle = IDL.Variant({
  'experimental' : IDL.Null,
  'oldSchool' : IDL.Null,
  'trap' : IDL.Null,
  'classic' : IDL.Null,
  'modern' : IDL.Null,
  'jazzInfluence' : IDL.Null,
});
export const BeatTexture = IDL.Variant({
  'smooth' : IDL.Null,
  'gritty' : IDL.Null,
  'upbeat' : IDL.Null,
  'melodic' : IDL.Null,
});
export const BeatCategory = IDL.Variant({
  'pop' : IDL.Null,
  'lofi' : IDL.Null,
  'rock' : IDL.Null,
  'hipHop' : IDL.Null,
  'electronic' : IDL.Null,
});
export const BeatFilter = IDL.Record({
  'style' : IDL.Opt(BeatStyle),
  'texture' : IDL.Opt(BeatTexture),
  'category' : IDL.Opt(BeatCategory),
});
export const PreviewType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
});
export const PreviewEntry = IDL.Record({
  'duration' : IDL.Nat,
  'assetId' : IDL.Text,
  'reference' : ExternalBlob,
  'description' : IDL.Opt(IDL.Text),
  'previewType' : PreviewType,
});
export const DeliveryMethod = IDL.Variant({
  'googleDrive' : IDL.Null,
  'zipFiles' : IDL.Null,
});
export const LicenseDocType = IDL.Variant({
  'pdf' : IDL.Null,
  'txt' : IDL.Null,
  'docx' : IDL.Null,
  'folder' : IDL.Null,
});
export const LicenseDocEntry = IDL.Record({
  'assetId' : IDL.Text,
  'reference' : ExternalBlob,
  'description' : IDL.Opt(IDL.Text),
  'docType' : LicenseDocType,
});
export const AudioFileType = IDL.Variant({
  'mp3' : IDL.Null,
  'wav' : IDL.Null,
  'stems' : IDL.Null,
});
export const AudioFileEntry = IDL.Record({
  'assetId' : IDL.Text,
  'reference' : ExternalBlob,
  'description' : IDL.Opt(IDL.Text),
  'fileType' : AudioFileType,
});
export const RightsType = IDL.Variant({
  'basicRight' : IDL.Null,
  'premiumRight' : IDL.Null,
  'exclusiveRight' : IDL.Null,
  'stems' : IDL.Null,
});
export const RightsFolder = IDL.Record({
  'freeDownload' : IDL.Bool,
  'sold' : IDL.Bool,
  'googleDriveLink' : IDL.Opt(IDL.Text),
  'zipFile' : IDL.Opt(ExternalBlob),
  'licenseDocs' : IDL.Vec(LicenseDocEntry),
  'audioFiles' : IDL.Vec(AudioFileEntry),
  'priceInCents' : IDL.Nat,
  'rightsType' : RightsType,
});
export const CoverArtType = IDL.Variant({
  'jpg' : IDL.Null,
  'png' : IDL.Null,
  'webp' : IDL.Null,
});
export const CoverArtEntry = IDL.Record({
  'assetId' : IDL.Text,
  'reference' : ExternalBlob,
  'description' : IDL.Opt(IDL.Text),
  'fileType' : CoverArtType,
});
export const Beat = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'preview' : PreviewEntry,
  'deliveryMethod' : DeliveryMethod,
  'rightsFolders' : IDL.Vec(RightsFolder),
  'style' : BeatStyle,
  'approved' : IDL.Bool,
  'texture' : BeatTexture,
  'category' : BeatCategory,
  'artist' : IDL.Text,
  'coverArt' : IDL.Vec(CoverArtEntry),
});
export const LiveStream = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'host' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const PageVisits = IDL.Record({
  'mva' : IDL.Nat,
  'forum' : IDL.Nat,
  'live' : IDL.Nat,
  'mixtapes' : IDL.Nat,
  'store' : IDL.Nat,
  'musicLinks' : IDL.Nat,
  'showcase' : IDL.Nat,
});
export const DailyVisit = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
export const AnalyticsData = IDL.Record({
  'pageVisits' : PageVisits,
  'dailyVisits' : IDL.Vec(DailyVisit),
  'totalVisits' : IDL.Nat,
  'uniqueVisitors' : IDL.Nat,
});
export const Mixtape = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'externalLinks' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'songs' : IDL.Vec(ExternalBlob),
  'approved' : IDL.Bool,
  'uploader' : IDL.Principal,
  'artistName' : IDL.Text,
  'coverArt' : IDL.Opt(ExternalBlob),
});
export const Showcase = IDL.Record({
  'id' : IDL.Text,
  'externalLink' : IDL.Opt(IDL.Text),
  'songName' : IDL.Text,
  'audioFile' : ExternalBlob,
  'style' : BeatStyle,
  'approved' : IDL.Bool,
  'beatId' : IDL.Opt(IDL.Text),
  'texture' : BeatTexture,
  'category' : BeatCategory,
  'artistName' : IDL.Text,
  'coverArt' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'isCreator' : IDL.Bool,
  'name' : IDL.Text,
});
export const Section = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'creatorName' : IDL.Text,
  'linkSharingEnabled' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'sectionId' : IDL.Text,
  'message' : IDL.Text,
});
export const Milestone = IDL.Record({
  'media' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'date' : IDL.Text,
  'description' : IDL.Text,
});
export const MixtapeSubmissionFeeConfig = IDL.Record({
  'enabled' : IDL.Bool,
  'priceInCents' : IDL.Nat,
});
export const MusicLink = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'platform' : Platform,
  'coverArt' : IDL.Opt(ExternalBlob),
  'releaseDate' : IDL.Opt(IDL.Text),
});
export const Replay = IDL.Record({
  'replayUrl' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ShowcaseHighlight = IDL.Record({
  'mixtapeId' : IDL.Text,
  'highlightedSong' : ExternalBlob,
  'artistName' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Show = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const PageType = IDL.Variant({
  'mva' : IDL.Null,
  'forum' : IDL.Null,
  'live' : IDL.Null,
  'mixtapes' : IDL.Null,
  'store' : IDL.Null,
  'musicLinks' : IDL.Null,
  'showcase' : IDL.Null,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExcludedVisitor' : IDL.Func([IDL.Principal], [], []),
  'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addMusicLink' : IDL.Func(
      [IDL.Text, Platform, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'addReplay' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addUpcomingShow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'approveAllShowcases' : IDL.Func([], [], []),
  'approveMixtape' : IDL.Func([IDL.Text], [], []),
  'approveShowcase' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdateMessages' : IDL.Func([IDL.Vec(MessageUpdate)], [], []),
  'canGetBasicRightsWithLicense' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'canGetExclusiveRightsWithLicense' : IDL.Func(
      [IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'canGetPremiumRightsWithLicense' : IDL.Func(
      [IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'canGetStemsRightsWithLicense' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'clearFeaturedBeat' : IDL.Func([], [], []),
  'clearRedirectUrl' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createSection' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
  'deleteBasicRightsLicense' : IDL.Func([], [], []),
  'deleteBeat' : IDL.Func([IDL.Text], [], []),
  'deleteExclusiveRightsLicense' : IDL.Func([], [], []),
  'deleteMessage' : IDL.Func([IDL.Text], [], []),
  'deleteMilestone' : IDL.Func([IDL.Text], [], []),
  'deleteMixtape' : IDL.Func([IDL.Text], [], []),
  'deleteMusicLink' : IDL.Func([IDL.Text], [], []),
  'deleteMvaPreview' : IDL.Func([], [], []),
  'deletePremiumRightsLicense' : IDL.Func([], [], []),
  'deleteReplay' : IDL.Func([IDL.Text], [], []),
  'deleteSection' : IDL.Func([IDL.Text], [], []),
  'deleteShowcase' : IDL.Func([IDL.Text], [], []),
  'deleteStemsRightsLicense' : IDL.Func([], [], []),
  'deleteUpcomingShow' : IDL.Func([IDL.Text], [], []),
  'endAllLiveStreams' : IDL.Func([], [], []),
  'endLiveStream' : IDL.Func([IDL.Text], [], []),
  'filterBeats' : IDL.Func([BeatFilter], [IDL.Vec(Beat)], ['query']),
  'getActiveLiveStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
  'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
  'getApprovedMixtapes' : IDL.Func([], [IDL.Vec(Mixtape)], ['query']),
  'getApprovedShowcases' : IDL.Func([], [IDL.Vec(Showcase)], ['query']),
  'getBasicRightsLicense' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getBeat' : IDL.Func([IDL.Text], [IDL.Opt(Beat)], ['query']),
  'getBeats' : IDL.Func([], [IDL.Vec(Beat)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExcludedVisitors' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getExclusiveRightsLicense' : IDL.Func(
      [],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getFeaturedBeat' : IDL.Func([], [IDL.Opt(Beat)], ['query']),
  'getGoogleDriveLink' : IDL.Func(
      [IDL.Text, RightsType, IDL.Opt(IDL.Text)],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'getLicenseFiles' : IDL.Func(
      [IDL.Text, RightsType, IDL.Opt(IDL.Text)],
      [IDL.Vec(ExternalBlob)],
      [],
    ),
  'getManySections' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(Section)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
  'getMixtapeSubmissionFeeConfig' : IDL.Func(
      [],
      [MixtapeSubmissionFeeConfig],
      ['query'],
    ),
  'getMusicLinks' : IDL.Func([], [IDL.Vec(MusicLink)], ['query']),
  'getMvaPreview' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getPendingMixtapes' : IDL.Func([], [IDL.Vec(Mixtape)], ['query']),
  'getPendingShowcases' : IDL.Func([], [IDL.Vec(Showcase)], ['query']),
  'getPremiumRightsLicense' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getPurchaseHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRedirectUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getReplays' : IDL.Func([], [IDL.Vec(Replay)], ['query']),
  'getRightsZipFile' : IDL.Func(
      [IDL.Text, RightsType, IDL.Opt(IDL.Text)],
      [IDL.Opt(ExternalBlob)],
      [],
    ),
  'getSection' : IDL.Func([IDL.Text], [IDL.Opt(Section)], ['query']),
  'getSectionLinkSharing' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
  'getShowcaseHighlights' : IDL.Func(
      [],
      [IDL.Vec(ShowcaseHighlight)],
      ['query'],
    ),
  'getStemsRightsLicense' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUpcomingShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isExcludedVisitor' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'processOutcall' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'recordBeatPurchase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, RightsType],
      [],
      [],
    ),
  'recordSiteVisit' : IDL.Func([PageType], [], []),
  'rejectMixtape' : IDL.Func([IDL.Text], [], []),
  'removeExcludedVisitor' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMilestone' : IDL.Func([IDL.Text, Milestone], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setFeaturedBeat' : IDL.Func([IDL.Text], [], []),
  'setMixtapeSubmissionFeeConfig' : IDL.Func([IDL.Bool, IDL.Nat], [], []),
  'setRedirectUrl' : IDL.Func([IDL.Text], [], []),
  'setSectionLinkSharing' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setShowcaseHighlight' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'startLiveStream' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitMixtape' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Vec(ExternalBlob),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'submitShowcase' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        BeatCategory,
        BeatStyle,
        BeatTexture,
        IDL.Opt(IDL.Text),
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unmarkRightsAsSold' : IDL.Func([IDL.Text, RightsType], [], []),
  'updateBasicRightsLicense' : IDL.Func([ExternalBlob], [], []),
  'updateBeat' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        BeatCategory,
        BeatStyle,
        BeatTexture,
        IDL.Vec(CoverArtEntry),
        PreviewEntry,
        IDL.Vec(RightsFolder),
        DeliveryMethod,
      ],
      [],
      [],
    ),
  'updateExclusiveRightsLicense' : IDL.Func([ExternalBlob], [], []),
  'updateMilestoneOrder' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [],
      [],
    ),
  'updateMusicLink' : IDL.Func(
      [IDL.Text, Platform, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updatePremiumRightsLicense' : IDL.Func([ExternalBlob], [], []),
  'updateReplay' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateStemsRightsLicense' : IDL.Func([ExternalBlob], [], []),
  'updateUpcomingShow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'uploadBasicRightsLicense' : IDL.Func([ExternalBlob], [], []),
  'uploadBeat' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        BeatCategory,
        BeatStyle,
        BeatTexture,
        IDL.Vec(CoverArtEntry),
        PreviewEntry,
        IDL.Vec(RightsFolder),
        DeliveryMethod,
      ],
      [],
      [],
    ),
  'uploadExclusiveRightsLicense' : IDL.Func([ExternalBlob], [], []),
  'uploadMvaPreview' : IDL.Func([ExternalBlob], [], []),
  'uploadPremiumRightsLicense' : IDL.Func([ExternalBlob], [], []),
  'uploadStemsRightsLicense' : IDL.Func([ExternalBlob], [], []),
  'verifyBeatPurchase' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      ['query'],
    ),
  'verifyGuestBeatPurchase' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Platform = IDL.Variant({
    'soundcloud' : IDL.Null,
    'other' : IDL.Text,
    'spotify' : IDL.Null,
    'youtube' : IDL.Null,
    'appleMusic' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageUpdate = IDL.Record({
    'id' : IDL.Text,
    'updatedContent' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const BeatStyle = IDL.Variant({
    'experimental' : IDL.Null,
    'oldSchool' : IDL.Null,
    'trap' : IDL.Null,
    'classic' : IDL.Null,
    'modern' : IDL.Null,
    'jazzInfluence' : IDL.Null,
  });
  const BeatTexture = IDL.Variant({
    'smooth' : IDL.Null,
    'gritty' : IDL.Null,
    'upbeat' : IDL.Null,
    'melodic' : IDL.Null,
  });
  const BeatCategory = IDL.Variant({
    'pop' : IDL.Null,
    'lofi' : IDL.Null,
    'rock' : IDL.Null,
    'hipHop' : IDL.Null,
    'electronic' : IDL.Null,
  });
  const BeatFilter = IDL.Record({
    'style' : IDL.Opt(BeatStyle),
    'texture' : IDL.Opt(BeatTexture),
    'category' : IDL.Opt(BeatCategory),
  });
  const PreviewType = IDL.Variant({ 'audio' : IDL.Null, 'video' : IDL.Null });
  const PreviewEntry = IDL.Record({
    'duration' : IDL.Nat,
    'assetId' : IDL.Text,
    'reference' : ExternalBlob,
    'description' : IDL.Opt(IDL.Text),
    'previewType' : PreviewType,
  });
  const DeliveryMethod = IDL.Variant({
    'googleDrive' : IDL.Null,
    'zipFiles' : IDL.Null,
  });
  const LicenseDocType = IDL.Variant({
    'pdf' : IDL.Null,
    'txt' : IDL.Null,
    'docx' : IDL.Null,
    'folder' : IDL.Null,
  });
  const LicenseDocEntry = IDL.Record({
    'assetId' : IDL.Text,
    'reference' : ExternalBlob,
    'description' : IDL.Opt(IDL.Text),
    'docType' : LicenseDocType,
  });
  const AudioFileType = IDL.Variant({
    'mp3' : IDL.Null,
    'wav' : IDL.Null,
    'stems' : IDL.Null,
  });
  const AudioFileEntry = IDL.Record({
    'assetId' : IDL.Text,
    'reference' : ExternalBlob,
    'description' : IDL.Opt(IDL.Text),
    'fileType' : AudioFileType,
  });
  const RightsType = IDL.Variant({
    'basicRight' : IDL.Null,
    'premiumRight' : IDL.Null,
    'exclusiveRight' : IDL.Null,
    'stems' : IDL.Null,
  });
  const RightsFolder = IDL.Record({
    'freeDownload' : IDL.Bool,
    'sold' : IDL.Bool,
    'googleDriveLink' : IDL.Opt(IDL.Text),
    'zipFile' : IDL.Opt(ExternalBlob),
    'licenseDocs' : IDL.Vec(LicenseDocEntry),
    'audioFiles' : IDL.Vec(AudioFileEntry),
    'priceInCents' : IDL.Nat,
    'rightsType' : RightsType,
  });
  const CoverArtType = IDL.Variant({
    'jpg' : IDL.Null,
    'png' : IDL.Null,
    'webp' : IDL.Null,
  });
  const CoverArtEntry = IDL.Record({
    'assetId' : IDL.Text,
    'reference' : ExternalBlob,
    'description' : IDL.Opt(IDL.Text),
    'fileType' : CoverArtType,
  });
  const Beat = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'preview' : PreviewEntry,
    'deliveryMethod' : DeliveryMethod,
    'rightsFolders' : IDL.Vec(RightsFolder),
    'style' : BeatStyle,
    'approved' : IDL.Bool,
    'texture' : BeatTexture,
    'category' : BeatCategory,
    'artist' : IDL.Text,
    'coverArt' : IDL.Vec(CoverArtEntry),
  });
  const LiveStream = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'host' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const PageVisits = IDL.Record({
    'mva' : IDL.Nat,
    'forum' : IDL.Nat,
    'live' : IDL.Nat,
    'mixtapes' : IDL.Nat,
    'store' : IDL.Nat,
    'musicLinks' : IDL.Nat,
    'showcase' : IDL.Nat,
  });
  const DailyVisit = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const AnalyticsData = IDL.Record({
    'pageVisits' : PageVisits,
    'dailyVisits' : IDL.Vec(DailyVisit),
    'totalVisits' : IDL.Nat,
    'uniqueVisitors' : IDL.Nat,
  });
  const Mixtape = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'externalLinks' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'songs' : IDL.Vec(ExternalBlob),
    'approved' : IDL.Bool,
    'uploader' : IDL.Principal,
    'artistName' : IDL.Text,
    'coverArt' : IDL.Opt(ExternalBlob),
  });
  const Showcase = IDL.Record({
    'id' : IDL.Text,
    'externalLink' : IDL.Opt(IDL.Text),
    'songName' : IDL.Text,
    'audioFile' : ExternalBlob,
    'style' : BeatStyle,
    'approved' : IDL.Bool,
    'beatId' : IDL.Opt(IDL.Text),
    'texture' : BeatTexture,
    'category' : BeatCategory,
    'artistName' : IDL.Text,
    'coverArt' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'isCreator' : IDL.Bool, 'name' : IDL.Text });
  const Section = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'creatorName' : IDL.Text,
    'linkSharingEnabled' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'sectionId' : IDL.Text,
    'message' : IDL.Text,
  });
  const Milestone = IDL.Record({
    'media' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'date' : IDL.Text,
    'description' : IDL.Text,
  });
  const MixtapeSubmissionFeeConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'priceInCents' : IDL.Nat,
  });
  const MusicLink = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'platform' : Platform,
    'coverArt' : IDL.Opt(ExternalBlob),
    'releaseDate' : IDL.Opt(IDL.Text),
  });
  const Replay = IDL.Record({
    'replayUrl' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ShowcaseHighlight = IDL.Record({
    'mixtapeId' : IDL.Text,
    'highlightedSong' : ExternalBlob,
    'artistName' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Show = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const PageType = IDL.Variant({
    'mva' : IDL.Null,
    'forum' : IDL.Null,
    'live' : IDL.Null,
    'mixtapes' : IDL.Null,
    'store' : IDL.Null,
    'musicLinks' : IDL.Null,
    'showcase' : IDL.Null,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExcludedVisitor' : IDL.Func([IDL.Principal], [], []),
    'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addMusicLink' : IDL.Func(
        [
          IDL.Text,
          Platform,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addReplay' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addUpcomingShow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'approveAllShowcases' : IDL.Func([], [], []),
    'approveMixtape' : IDL.Func([IDL.Text], [], []),
    'approveShowcase' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdateMessages' : IDL.Func([IDL.Vec(MessageUpdate)], [], []),
    'canGetBasicRightsWithLicense' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'canGetExclusiveRightsWithLicense' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'canGetPremiumRightsWithLicense' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'canGetStemsRightsWithLicense' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'clearFeaturedBeat' : IDL.Func([], [], []),
    'clearRedirectUrl' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createSection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'deleteBasicRightsLicense' : IDL.Func([], [], []),
    'deleteBeat' : IDL.Func([IDL.Text], [], []),
    'deleteExclusiveRightsLicense' : IDL.Func([], [], []),
    'deleteMessage' : IDL.Func([IDL.Text], [], []),
    'deleteMilestone' : IDL.Func([IDL.Text], [], []),
    'deleteMixtape' : IDL.Func([IDL.Text], [], []),
    'deleteMusicLink' : IDL.Func([IDL.Text], [], []),
    'deleteMvaPreview' : IDL.Func([], [], []),
    'deletePremiumRightsLicense' : IDL.Func([], [], []),
    'deleteReplay' : IDL.Func([IDL.Text], [], []),
    'deleteSection' : IDL.Func([IDL.Text], [], []),
    'deleteShowcase' : IDL.Func([IDL.Text], [], []),
    'deleteStemsRightsLicense' : IDL.Func([], [], []),
    'deleteUpcomingShow' : IDL.Func([IDL.Text], [], []),
    'endAllLiveStreams' : IDL.Func([], [], []),
    'endLiveStream' : IDL.Func([IDL.Text], [], []),
    'filterBeats' : IDL.Func([BeatFilter], [IDL.Vec(Beat)], ['query']),
    'getActiveLiveStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
    'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
    'getApprovedMixtapes' : IDL.Func([], [IDL.Vec(Mixtape)], ['query']),
    'getApprovedShowcases' : IDL.Func([], [IDL.Vec(Showcase)], ['query']),
    'getBasicRightsLicense' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getBeat' : IDL.Func([IDL.Text], [IDL.Opt(Beat)], ['query']),
    'getBeats' : IDL.Func([], [IDL.Vec(Beat)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExcludedVisitors' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getExclusiveRightsLicense' : IDL.Func(
        [],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getFeaturedBeat' : IDL.Func([], [IDL.Opt(Beat)], ['query']),
    'getGoogleDriveLink' : IDL.Func(
        [IDL.Text, RightsType, IDL.Opt(IDL.Text)],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'getLicenseFiles' : IDL.Func(
        [IDL.Text, RightsType, IDL.Opt(IDL.Text)],
        [IDL.Vec(ExternalBlob)],
        [],
      ),
    'getManySections' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(Section)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
    'getMixtapeSubmissionFeeConfig' : IDL.Func(
        [],
        [MixtapeSubmissionFeeConfig],
        ['query'],
      ),
    'getMusicLinks' : IDL.Func([], [IDL.Vec(MusicLink)], ['query']),
    'getMvaPreview' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getPendingMixtapes' : IDL.Func([], [IDL.Vec(Mixtape)], ['query']),
    'getPendingShowcases' : IDL.Func([], [IDL.Vec(Showcase)], ['query']),
    'getPremiumRightsLicense' : IDL.Func(
        [],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getPurchaseHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRedirectUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getReplays' : IDL.Func([], [IDL.Vec(Replay)], ['query']),
    'getRightsZipFile' : IDL.Func(
        [IDL.Text, RightsType, IDL.Opt(IDL.Text)],
        [IDL.Opt(ExternalBlob)],
        [],
      ),
    'getSection' : IDL.Func([IDL.Text], [IDL.Opt(Section)], ['query']),
    'getSectionLinkSharing' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
    'getShowcaseHighlights' : IDL.Func(
        [],
        [IDL.Vec(ShowcaseHighlight)],
        ['query'],
      ),
    'getStemsRightsLicense' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUpcomingShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isExcludedVisitor' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'processOutcall' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'recordBeatPurchase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, RightsType],
        [],
        [],
      ),
    'recordSiteVisit' : IDL.Func([PageType], [], []),
    'rejectMixtape' : IDL.Func([IDL.Text], [], []),
    'removeExcludedVisitor' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMilestone' : IDL.Func([IDL.Text, Milestone], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setFeaturedBeat' : IDL.Func([IDL.Text], [], []),
    'setMixtapeSubmissionFeeConfig' : IDL.Func([IDL.Bool, IDL.Nat], [], []),
    'setRedirectUrl' : IDL.Func([IDL.Text], [], []),
    'setSectionLinkSharing' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setShowcaseHighlight' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'startLiveStream' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitMixtape' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Vec(ExternalBlob),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'submitShowcase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          BeatCategory,
          BeatStyle,
          BeatTexture,
          IDL.Opt(IDL.Text),
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unmarkRightsAsSold' : IDL.Func([IDL.Text, RightsType], [], []),
    'updateBasicRightsLicense' : IDL.Func([ExternalBlob], [], []),
    'updateBeat' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          BeatCategory,
          BeatStyle,
          BeatTexture,
          IDL.Vec(CoverArtEntry),
          PreviewEntry,
          IDL.Vec(RightsFolder),
          DeliveryMethod,
        ],
        [],
        [],
      ),
    'updateExclusiveRightsLicense' : IDL.Func([ExternalBlob], [], []),
    'updateMilestoneOrder' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [],
        [],
      ),
    'updateMusicLink' : IDL.Func(
        [
          IDL.Text,
          Platform,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updatePremiumRightsLicense' : IDL.Func([ExternalBlob], [], []),
    'updateReplay' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateStemsRightsLicense' : IDL.Func([ExternalBlob], [], []),
    'updateUpcomingShow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'uploadBasicRightsLicense' : IDL.Func([ExternalBlob], [], []),
    'uploadBeat' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          BeatCategory,
          BeatStyle,
          BeatTexture,
          IDL.Vec(CoverArtEntry),
          PreviewEntry,
          IDL.Vec(RightsFolder),
          DeliveryMethod,
        ],
        [],
        [],
      ),
    'uploadExclusiveRightsLicense' : IDL.Func([ExternalBlob], [], []),
    'uploadMvaPreview' : IDL.Func([ExternalBlob], [], []),
    'uploadPremiumRightsLicense' : IDL.Func([ExternalBlob], [], []),
    'uploadStemsRightsLicense' : IDL.Func([ExternalBlob], [], []),
    'verifyBeatPurchase' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        ['query'],
      ),
    'verifyGuestBeatPurchase' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };