/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'pageVisits' : PageVisits,
  'dailyVisits' : Array<DailyVisit>,
  'totalVisits' : bigint,
  'uniqueVisitors' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AudioFileEntry {
  'assetId' : string,
  'reference' : ExternalBlob,
  'description' : [] | [string],
  'fileType' : AudioFileType,
}
export type AudioFileType = { 'mp3' : null } |
  { 'wav' : null } |
  { 'stems' : null };
export interface Beat {
  'id' : string,
  'title' : string,
  'preview' : PreviewEntry,
  'deliveryMethod' : DeliveryMethod,
  'rightsFolders' : Array<RightsFolder>,
  'style' : BeatStyle,
  'approved' : boolean,
  'texture' : BeatTexture,
  'category' : BeatCategory,
  'artist' : string,
  'coverArt' : Array<CoverArtEntry>,
}
export type BeatCategory = { 'pop' : null } |
  { 'lofi' : null } |
  { 'rock' : null } |
  { 'hipHop' : null } |
  { 'electronic' : null };
export interface BeatFilter {
  'style' : [] | [BeatStyle],
  'texture' : [] | [BeatTexture],
  'category' : [] | [BeatCategory],
}
export type BeatStyle = { 'experimental' : null } |
  { 'oldSchool' : null } |
  { 'trap' : null } |
  { 'classic' : null } |
  { 'modern' : null } |
  { 'jazzInfluence' : null };
export type BeatTexture = { 'smooth' : null } |
  { 'gritty' : null } |
  { 'upbeat' : null } |
  { 'melodic' : null };
export interface CoverArtEntry {
  'assetId' : string,
  'reference' : ExternalBlob,
  'description' : [] | [string],
  'fileType' : CoverArtType,
}
export type CoverArtType = { 'jpg' : null } |
  { 'png' : null } |
  { 'webp' : null };
export interface DailyVisit { 'date' : string, 'count' : bigint }
export type DeliveryMethod = { 'googleDrive' : null } |
  { 'zipFiles' : null };
export type ExternalBlob = Uint8Array;
export interface LicenseDocEntry {
  'assetId' : string,
  'reference' : ExternalBlob,
  'description' : [] | [string],
  'docType' : LicenseDocType,
}
export type LicenseDocType = { 'pdf' : null } |
  { 'txt' : null } |
  { 'docx' : null } |
  { 'folder' : null };
export interface LiveStream {
  'id' : string,
  'title' : string,
  'host' : string,
  'description' : string,
  'isActive' : boolean,
}
export interface Message {
  'id' : string,
  'principal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'sectionId' : string,
  'message' : string,
}
export interface MessageUpdate { 'id' : string, 'updatedContent' : string }
export interface Milestone {
  'media' : [] | [ExternalBlob],
  'title' : string,
  'order' : bigint,
  'date' : string,
  'description' : string,
}
export interface Mixtape {
  'id' : string,
  'title' : string,
  'externalLinks' : Array<string>,
  'description' : string,
  'songs' : Array<ExternalBlob>,
  'approved' : boolean,
  'uploader' : Principal,
  'artistName' : string,
  'coverArt' : [] | [ExternalBlob],
}
export interface MixtapeSubmissionFeeConfig {
  'enabled' : boolean,
  'priceInCents' : bigint,
}
export interface MusicLink {
  'url' : string,
  'title' : string,
  'platform' : Platform,
  'coverArt' : [] | [ExternalBlob],
  'releaseDate' : [] | [string],
}
export type PageType = { 'mva' : null } |
  { 'forum' : null } |
  { 'live' : null } |
  { 'mixtapes' : null } |
  { 'store' : null } |
  { 'musicLinks' : null } |
  { 'showcase' : null };
export interface PageVisits {
  'mva' : bigint,
  'forum' : bigint,
  'live' : bigint,
  'mixtapes' : bigint,
  'store' : bigint,
  'musicLinks' : bigint,
  'showcase' : bigint,
}
export type Platform = { 'soundcloud' : null } |
  { 'other' : string } |
  { 'spotify' : null } |
  { 'youtube' : null } |
  { 'appleMusic' : null };
export interface PreviewEntry {
  'duration' : bigint,
  'assetId' : string,
  'reference' : ExternalBlob,
  'description' : [] | [string],
  'previewType' : PreviewType,
}
export type PreviewType = { 'audio' : null } |
  { 'video' : null };
export interface Replay {
  'replayUrl' : string,
  'title' : string,
  'description' : string,
}
export interface RightsFolder {
  'freeDownload' : boolean,
  'sold' : boolean,
  'googleDriveLink' : [] | [string],
  'zipFile' : [] | [ExternalBlob],
  'licenseDocs' : Array<LicenseDocEntry>,
  'audioFiles' : Array<AudioFileEntry>,
  'priceInCents' : bigint,
  'rightsType' : RightsType,
}
export type RightsType = { 'basicRight' : null } |
  { 'premiumRight' : null } |
  { 'exclusiveRight' : null } |
  { 'stems' : null };
export interface Section {
  'id' : string,
  'title' : string,
  'creator' : string,
  'createdAt' : bigint,
  'description' : string,
  'creatorName' : string,
  'linkSharingEnabled' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Show {
  'title' : string,
  'date' : string,
  'time' : string,
  'description' : string,
}
export interface Showcase {
  'id' : string,
  'externalLink' : [] | [string],
  'songName' : string,
  'audioFile' : ExternalBlob,
  'style' : BeatStyle,
  'approved' : boolean,
  'beatId' : [] | [string],
  'texture' : BeatTexture,
  'category' : BeatCategory,
  'artistName' : string,
  'coverArt' : [] | [ExternalBlob],
}
export interface ShowcaseHighlight {
  'mixtapeId' : string,
  'highlightedSong' : ExternalBlob,
  'artistName' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'isCreator' : boolean, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExcludedVisitor' : ActorMethod<[Principal], undefined>,
  'addMessage' : ActorMethod<[string, string, string], undefined>,
  'addMusicLink' : ActorMethod<
    [string, Platform, string, [] | [string], [] | [ExternalBlob]],
    undefined
  >,
  'addReplay' : ActorMethod<[string, string, string, string], undefined>,
  'addUpcomingShow' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'approveAllShowcases' : ActorMethod<[], undefined>,
  'approveMixtape' : ActorMethod<[string], undefined>,
  'approveShowcase' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateMessages' : ActorMethod<[Array<MessageUpdate>], undefined>,
  'canGetBasicRightsWithLicense' : ActorMethod<[string], boolean>,
  'canGetExclusiveRightsWithLicense' : ActorMethod<[string], boolean>,
  'canGetPremiumRightsWithLicense' : ActorMethod<[string], boolean>,
  'canGetStemsRightsWithLicense' : ActorMethod<[string], boolean>,
  'clearFeaturedBeat' : ActorMethod<[], undefined>,
  'clearRedirectUrl' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createSection' : ActorMethod<[string, string, string, boolean], undefined>,
  'deleteBasicRightsLicense' : ActorMethod<[], undefined>,
  'deleteBeat' : ActorMethod<[string], undefined>,
  'deleteExclusiveRightsLicense' : ActorMethod<[], undefined>,
  'deleteMessage' : ActorMethod<[string], undefined>,
  'deleteMilestone' : ActorMethod<[string], undefined>,
  'deleteMixtape' : ActorMethod<[string], undefined>,
  'deleteMusicLink' : ActorMethod<[string], undefined>,
  'deleteMvaPreview' : ActorMethod<[], undefined>,
  'deletePremiumRightsLicense' : ActorMethod<[], undefined>,
  'deleteReplay' : ActorMethod<[string], undefined>,
  'deleteSection' : ActorMethod<[string], undefined>,
  'deleteShowcase' : ActorMethod<[string], undefined>,
  'deleteStemsRightsLicense' : ActorMethod<[], undefined>,
  'deleteUpcomingShow' : ActorMethod<[string], undefined>,
  'endAllLiveStreams' : ActorMethod<[], undefined>,
  'endLiveStream' : ActorMethod<[string], undefined>,
  'filterBeats' : ActorMethod<[BeatFilter], Array<Beat>>,
  'getActiveLiveStreams' : ActorMethod<[], Array<LiveStream>>,
  'getAnalytics' : ActorMethod<[], AnalyticsData>,
  'getApprovedMixtapes' : ActorMethod<[], Array<Mixtape>>,
  'getApprovedShowcases' : ActorMethod<[], Array<Showcase>>,
  'getBasicRightsLicense' : ActorMethod<[], [] | [ExternalBlob]>,
  'getBeat' : ActorMethod<[string], [] | [Beat]>,
  'getBeats' : ActorMethod<[], Array<Beat>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExcludedVisitors' : ActorMethod<[], Array<Principal>>,
  'getExclusiveRightsLicense' : ActorMethod<[], [] | [ExternalBlob]>,
  'getFeaturedBeat' : ActorMethod<[], [] | [Beat]>,
  'getGoogleDriveLink' : ActorMethod<
    [string, RightsType, [] | [string]],
    [] | [string]
  >,
  'getLicenseFiles' : ActorMethod<
    [string, RightsType, [] | [string]],
    Array<ExternalBlob>
  >,
  'getManySections' : ActorMethod<[Array<string>], Array<Section>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getMilestones' : ActorMethod<[], Array<Milestone>>,
  'getMixtapeSubmissionFeeConfig' : ActorMethod<[], MixtapeSubmissionFeeConfig>,
  'getMusicLinks' : ActorMethod<[], Array<MusicLink>>,
  'getMvaPreview' : ActorMethod<[], [] | [ExternalBlob]>,
  'getPendingMixtapes' : ActorMethod<[], Array<Mixtape>>,
  'getPendingShowcases' : ActorMethod<[], Array<Showcase>>,
  'getPremiumRightsLicense' : ActorMethod<[], [] | [ExternalBlob]>,
  'getPurchaseHistory' : ActorMethod<[], Array<string>>,
  'getRedirectUrl' : ActorMethod<[], [] | [string]>,
  'getReplays' : ActorMethod<[], Array<Replay>>,
  'getRightsZipFile' : ActorMethod<
    [string, RightsType, [] | [string]],
    [] | [ExternalBlob]
  >,
  'getSection' : ActorMethod<[string], [] | [Section]>,
  'getSectionLinkSharing' : ActorMethod<[string], boolean>,
  'getSections' : ActorMethod<[], Array<Section>>,
  'getShowcaseHighlights' : ActorMethod<[], Array<ShowcaseHighlight>>,
  'getStemsRightsLicense' : ActorMethod<[], [] | [ExternalBlob]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUpcomingShows' : ActorMethod<[], Array<Show>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isExcludedVisitor' : ActorMethod<[Principal], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'processOutcall' : ActorMethod<[TransformationInput], TransformationOutput>,
  'recordBeatPurchase' : ActorMethod<
    [string, string, boolean, RightsType],
    undefined
  >,
  'recordSiteVisit' : ActorMethod<[PageType], undefined>,
  'rejectMixtape' : ActorMethod<[string], undefined>,
  'removeExcludedVisitor' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMilestone' : ActorMethod<[string, Milestone], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setFeaturedBeat' : ActorMethod<[string], undefined>,
  'setMixtapeSubmissionFeeConfig' : ActorMethod<[boolean, bigint], undefined>,
  'setRedirectUrl' : ActorMethod<[string], undefined>,
  'setSectionLinkSharing' : ActorMethod<[string, boolean], undefined>,
  'setShowcaseHighlight' : ActorMethod<
    [string, ExternalBlob, string],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'startLiveStream' : ActorMethod<[string, string, string, string], undefined>,
  'submitMixtape' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      Array<ExternalBlob>,
      Array<string>,
      [] | [string],
    ],
    undefined
  >,
  'submitShowcase' : ActorMethod<
    [
      string,
      string,
      string,
      BeatCategory,
      BeatStyle,
      BeatTexture,
      [] | [string],
      ExternalBlob,
      [] | [ExternalBlob],
      [] | [string],
    ],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unmarkRightsAsSold' : ActorMethod<[string, RightsType], undefined>,
  'updateBasicRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'updateBeat' : ActorMethod<
    [
      string,
      string,
      string,
      BeatCategory,
      BeatStyle,
      BeatTexture,
      Array<CoverArtEntry>,
      PreviewEntry,
      Array<RightsFolder>,
      DeliveryMethod,
    ],
    undefined
  >,
  'updateExclusiveRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'updateMilestoneOrder' : ActorMethod<[Array<[string, bigint]>], undefined>,
  'updateMusicLink' : ActorMethod<
    [string, Platform, string, [] | [string], [] | [ExternalBlob]],
    undefined
  >,
  'updatePremiumRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'updateReplay' : ActorMethod<[string, string, string, string], undefined>,
  'updateStemsRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'updateUpcomingShow' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'uploadBasicRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'uploadBeat' : ActorMethod<
    [
      string,
      string,
      string,
      BeatCategory,
      BeatStyle,
      BeatTexture,
      Array<CoverArtEntry>,
      PreviewEntry,
      Array<RightsFolder>,
      DeliveryMethod,
    ],
    undefined
  >,
  'uploadExclusiveRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'uploadMvaPreview' : ActorMethod<[ExternalBlob], undefined>,
  'uploadPremiumRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'uploadStemsRightsLicense' : ActorMethod<[ExternalBlob], undefined>,
  'verifyBeatPurchase' : ActorMethod<[string, [] | [string]], boolean>,
  'verifyGuestBeatPurchase' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];